/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const NewLazyImport = createFileRoute('/new')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const NumbersNumberIdLazyImport = createFileRoute('/numbers/$numberId')()

// Create/Update Routes

const NewLazyRoute = NewLazyImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/new.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NumbersNumberIdLazyRoute = NumbersNumberIdLazyImport.update({
  id: '/numbers/$numberId',
  path: '/numbers/$numberId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/numbers/$numberId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewLazyImport
      parentRoute: typeof rootRoute
    }
    '/numbers/$numberId': {
      id: '/numbers/$numberId'
      path: '/numbers/$numberId'
      fullPath: '/numbers/$numberId'
      preLoaderRoute: typeof NumbersNumberIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/new': typeof NewLazyRoute
  '/numbers/$numberId': typeof NumbersNumberIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/new': typeof NewLazyRoute
  '/numbers/$numberId': typeof NumbersNumberIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/new': typeof NewLazyRoute
  '/numbers/$numberId': typeof NumbersNumberIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/new' | '/numbers/$numberId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/new' | '/numbers/$numberId'
  id: '__root__' | '/' | '/about' | '/new' | '/numbers/$numberId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  NewLazyRoute: typeof NewLazyRoute
  NumbersNumberIdLazyRoute: typeof NumbersNumberIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  NewLazyRoute: NewLazyRoute,
  NumbersNumberIdLazyRoute: NumbersNumberIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/new",
        "/numbers/$numberId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/new": {
      "filePath": "new.lazy.tsx"
    },
    "/numbers/$numberId": {
      "filePath": "numbers/$numberId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
